/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:24a58a21-f486-4fa8-98b1-d45656011794",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_fvPRONbCq",
    "aws_user_pools_web_client_id": "47k2cnqcdm0dh4jbreg8gapnu0",
    "oauth": {
        "domain": "picapp32ab6981-32ab6981-staging.auth.eu-west-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
